build:
  main: cmd/tunnel/main.go
  binary: tunnel
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
    - dragonfly
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6

nfpm:
  formats:
    - deb
  vendor: "LabStack"
  homepage: "https://labstack.com/docs/diy/tunnel"
  maintainer: "Vishal Rana <vr@labstack.com>"
  description: "Tunnel lets you expose local servers to internet securely - ngrok alternative, compatible with SSH client."
  license: "MIT"
  
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    darwin: mac
    linux: linux
    windows: windows
  files:
    - README.md
    - LICENSE
release:
  draft: true